### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by Damov** [ImperialCollegeLondon/xbeam#4]
Hey,

I have some problems with the make file. Every time I include xbeam in my python file, I am getting:

`OSError: libxbeam.so: undefined symbol: dgesv_`

Please, help.
Daniel

**Comment by fonsocarre** [comment]
Hi @Damov 
First, `xbeam` and `sharpy` do not have an official release yet, and as such, the software is not intended for non-developers users, and no support is offered yet. However, with the very limited information I have from your problem, I could advise you to check that `lapack` is installed and in the LD_LIBRARY_PATH environment. If you are using ubuntu, make sure `liblapack-dev` (or something similar, I don't use ubuntu) is installed.

**Comment by Damov** [comment]
Hey, yes thanks for your reply. I've changed the line 33 in the makefile in `/src` folder as followed:

`	$(FCOMP) $(INCLUDE) -o $@ $(BASE_OBJS) $(LDFLAGS) $^`

Now it works.

Daniel
