### ISSUE TITLE
Dimension mismatch in q vector with rigid body degrees of freedom

### ISSUE THREAD

**Issue by ngoiz** [ImperialCollegeLondon/xbeam#5]
When running in debug mode a prescribed structural problem `cbeam3` comes with a runtime error of a mismatch of 10 degrees of freedom when building `q` (line `1218` in `cbeam3_solve.f90`). The simulation stops after this error. 

However, when running in normal mode, the error is ignored and the simulation proceeds as normal.

**Comment by ArturoMS13** [comment]
I think I fixed it. Let me know it if works when you get feedback from Ignacio

**Comment by ngoiz** [comment]
Fixed, thanks @ArturoMS13 !
