### ISSUE TITLE
Typo bug in dummy variables in xbeam_solv

### ISSUE THREAD

**Issue by jkkr2** [ImperialCollegeLondon/xbeam#8]
Hi,
I just tried to build xbeam with Intel OneAPI classic Fortran compiler. I got an error message in xbeam_solv.f90 line 2006:
`
        call xbeam_asbly_dynamic(numdof,&
                                 n_node,&
                                 n_elem,&
                                 elem,&
                                 node,&
                                 pos_ini,&
                                 psi_ini,&
                                 pos_ini,& ! pos_def,&
                                 psi_ini,& ! psi_def,&
                                 pos_dot_def,&
                                 psi_dot_def,&
                                 pos_ddot_def,&
                                 psi_ddot_def,&
                                 dQdt(1:6),&
                                 dQddt(1:6),&
                                 dQdt(7:10),& ! bug in code: dQdt(7:0)
                                 MRS,&
                                 MRR,&
                                 CRS,&
                                 CRR,&
                                 CQR,&
                                 CQQ,&
                                 KRS,&
                                 Frigid,&
                                 Qrigid,&
                                 options,&
                                 Cao)`
So I think  **dQdt(7:10)** is meant instead of  **dQdt(7:0)**. With this change there are no build errors and the lib is built.

**Comment by ArturoMS13** [comment]
Hi jkkr2,

I think you are right.

Thank you for reporting it!
